name: CI

on: [push]

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:
    
    - uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Build"
      uses: okteto/build@master
      with:
        tag: registry.cloud.okteto.net/sujith-mn/simple-servlet:${{ github.sha }}